### ISSUE TITLE
Issue building example on Windows machine

### ISSUE THREAD

**Issue by liamcurry** [mysterycommand/parcel-plugin-wasm-pack#64]
I'm having trouble building the `single` example on a Windows machine. The error looks like this:

```
$ yarn build
yarn run v1.12.3
$ parcel build src/index.html --no-minify --no-cache
×  C:\Users\sagan\Downloads\single\src\lib.rs:1:17: Cannot resolve dependency '../
pkgparcel_plugin_wasm_pack_examples_single.js' at 'C:\Users\sagan\Downloads\single
\pkgparcel_plugin_wasm_pack_examples_single.js'
    at Resolver.resolve (C:\Users\sagan\Downloads\single\node_modules\parcel-bundl
er\src\Resolver.js:71:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comman
d.
```

There seems to be a missing slash in `\pkgparcel_plugin_wasm_pack_examples_single.js`

**Comment by mysterycommand** [comment]
Hi @liamcurry, thank you for your interest in my little plugin. I'm still working on docs for all this and will try to get those out next week. I don't have a Windows machine to test this out on, so I may need to ask you to do some debugging if you're up for it. I'd love to get this figured out with you.

So I think that path that is broken there is what's called the `initPath` in the `WasmPackAsset` and it's added to Parcel's dependency tree here: [`WasmPackAsset.js#L206`](https://github.com/mysterycommand/parcel-plugin-wasm-pack/blob/master/src/WasmPackAsset.js#L206). That `rel` function there comes from [`helpers.js#L56-L64`](https://github.com/mysterycommand/parcel-plugin-wasm-pack/blob/master/src/helpers.js#L56-L64) and has this funny line in it: [`helpers.js#L63`](https://github.com/mysterycommand/parcel-plugin-wasm-pack/blob/master/src/helpers.js#L63) which think I just sort of blindly borrowed from here: [`catsigma/parcel-plugin-wasm.rs/WASMbindgenAsset.js#L143`](https://github.com/catsigma/parcel-plugin-wasm.rs/blob/master/WASMbindgenAsset.js#L143) while I was porting/refactoring/converting that project into this one.

So that `replace` call has this weird/fascinating behavior:
```js
const str = '..\\pkg\\test-test.js'.replace('\\', '/');
console.log(str);
// "../pkg\test-test.js"
```
What I'd love to find out is if this `replace` call is even necessary at all. Currently all the tests in [helpers.test.js](https://github.com/mysterycommand/parcel-plugin-wasm-pack/blob/master/src/helpers.test.js) pass without it. Maybe the original `parcel-plugin-wasm.rs`'s author @catsigma can shed some light here?

Okay, so, if you're up for it, I'd love it if you could try a couple of things:

1. From the root of your clone run `yarn` and then `yarn link` and then from the `examples/single` directory run `yarn link parcel-plugin-wasm-pack`
2. Add a line above [`helpers.js#L63`](https://github.com/mysterycommand/parcel-plugin-wasm-pack/blob/master/src/helpers.js#L63) with `console.log({ from, to, relativePath });`
3. Remove the `replace` call and see if that fixes the issue
    - **if it does fix the issue:** add a new assertion after [helpers.test.js#L93](https://github.com/mysterycommand/parcel-plugin-wasm-pack/blob/master/src/helpers.test.js#L93) that demonstrates that the `from` and `to` values from 2. return the `relativePath` value from same
    - **if it does _not_ fix the issue:** I guess we need a new/better `replace` call, but I'm not sure what it's arguments should be without knowing the values of `from`, `to`, and `relativePath` from 2

… I know that's kind of a lot, and I don't know if you have time or interest in any of this. I'd love to get this working, and would gladly accept a PR that makes the necessary changes, adds tests that would've caught this error in the first place, and that adds yourself to a `contributors` field in `package.json`. All of course, totally at your discretion.

**Comment by pocesar** [comment]
the author from parcel-plugin-wasm doesn't seem to know that `replace` with a string replaces only one instance, if he wants to replace all, he should be using `replace(//g, '/')` (which is kinda worrying that he doesn't know that, or have no tests for that).

using `path.join` is the only way to guarantee portability between OS paths. or at least `split(/[\\\/]/g)` then join using `path.sep`.

**Comment by mysterycommand** [comment]
Ahaha, @pocesar thanks for this. I'm still not super clear what the original intent here is, but in a recent PR I see @catsigma using the global RegExp version you recommend. So I guess we'll go with that providing my tests still pass … as I've said I don't have a Windows machine to verify this on, but if you or @liamcurry wouldn't mind helping me verify the fix I'd sure appreciate it.
